# -*- mode: ruby -*-
# vi: set ft=ruby :

# Сервер 2 дээр одоо зөвхөн worker2,3 -ийг асаана.
# Хэрэв олныг асаах бол доорх *WorkerCount* -ийн
# утгыг нэмнэ. Ингэж нэмэхдээ Сервер 1 дээр
# тохируулсан сүлжээний хаягтай давхцаж байгаа
# эсэхийг нягтлаж асаах хэрэгтэй.
#
# bootstrap.sh дотор instance асахдаа ямар коммандуудыг
# ажиллуулахыг бичиж өгсөн.

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Kubernetes Worker Nodes
  WorkerCount = 2

  (1..WorkerCount).each do |i|

    config.vm.define "kworker#{i+1}" do |workernode|

      workernode.vm.box               = "generic/ubuntu2004"
      workernode.vm.box_check_update  = false
      workernode.vm.box_version       = "3.3.0"
      workernode.vm.hostname          = "kworker#{i+1}.example.com"

      workernode.vm.network "public_network", ip: "192.168.55.23#{i+1}"

      workernode.vm.provider :virtualbox do |v|
        v.name   = "kworker#{i+1}"
        v.memory = 16384
        v.cpus   = 4
      end

    end

  end

end
