# -*- mode: ruby -*-
# vi: set ft=ruby :

# Сервер 2 дээр Master node 3 ажиллана.
#
# Сүлжээний хаягууд:
#   Master node 3: 192.168.55.213
#
# bootstrap.sh дотор instance асахдаа ямар коммандуудыг
# ажиллуулахыг бичиж өгсөн.


ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "kmaster3" do |masternode|
    masternode.vm.box               = "generic/ubuntu2004"
    masternode.vm.box_check_update  = false
    masternode.vm.box_version       = "3.3.0"
    masternode.vm.hostname          = "kmaster3.example.com"

    masternode.vm.network "public_network", ip: "192.168.55.213"

    masternode.vm.provider :virtualbox do |v|
      v.name   = "kmaster3"
      v.memory = 16384
      v.cpus   = 4
    end

  end

end

