apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.3.211"
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: "192.168.3.110:6443"
etcd:
  external:
    endpoints:
      - https://${ETCD1_IP}:2379
      - https://${ETCD2_IP}:2379
      - https://${ETCD3_IP}:2379
      caFile: /etc/kubernetes/pki/etcd/ca.pem
      certFile: /etc/kubernetes/pki/etcd/etcd.pem
      keyFile: /etc/kubernetes/pki/etcd/etcd-key.pem
networking:
  podSubnet: "10.244.0.0/24"
  serviceSubnet: "10.96.0.0/16"
